/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;
import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\56\1\3\1\3\22\0\1\4\1\12\1\27"+
    "\1\12\1\12\1\12\1\12\1\11\1\25\1\26\1\17\1\24\1\5"+
    "\1\16\1\7\1\21\12\2\1\10\1\6\1\22\1\20\1\23\1\12"+
    "\1\12\1\34\1\30\1\36\1\46\1\33\1\42\1\45\1\37\1\44"+
    "\2\1\1\32\1\1\1\35\1\31\1\54\1\1\1\40\1\51\1\41"+
    "\1\53\1\1\1\55\1\47\1\52\1\1\1\12\1\0\1\12\1\12"+
    "\1\15\1\0\1\34\1\30\1\36\1\46\1\33\1\42\1\45\1\37"+
    "\1\44\2\1\1\32\1\1\1\35\1\31\1\54\1\1\1\40\1\51"+
    "\1\41\1\53\1\1\1\55\1\47\1\52\1\1\1\12\1\0\1\12"+
    "\7\0\1\56\33\0\1\14\35\0\1\14\2\0\1\13\37\0\1\13"+
    "\115\0\2\43\115\0\1\50\u1ea8\0\1\56\1\56\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\1\1\10\1\11\1\12\1\11\2\12\1\10"+
    "\1\13\1\14\1\1\12\2\1\1\3\2\1\1\3\2"+
    "\1\15\2\0\1\16\1\17\2\0\1\4\3\0\1\20"+
    "\2\2\1\21\1\22\22\2\1\23\1\24\1\25\1\23"+
    "\1\24\1\25\2\2\1\0\5\2\1\3\1\26\2\0"+
    "\2\2\1\27\1\2\1\0\1\2\1\30\1\0\1\2"+
    "\1\31\10\2\1\32\3\2\1\0\1\2\1\33\1\34"+
    "\1\0\2\2\1\35\1\2\1\0\2\2\1\0\1\2"+
    "\1\36\1\37\1\0\1\37\1\2\2\40\1\2\1\41"+
    "\1\0\4\2\1\42\1\43\1\2\1\0\2\2\1\0"+
    "\1\2\1\0\2\2\1\0\1\44\1\0\2\2\2\45"+
    "\2\46\1\47\1\0\3\2\1\50\1\51\2\52\1\2"+
    "\1\0\1\2\1\0\3\2\2\53\1\2\1\0\2\2"+
    "\1\54\1\0\1\2\1\0\1\2\2\55\1\2\1\0"+
    "\1\2\1\56\1\0\2\2\1\0\1\2\2\57\1\2"+
    "\1\0\1\2\2\60\1\2\2\61\1\2\2\62\1\63"+
    "\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\57\0\57\0\274"+
    "\0\353\0\u011a\0\u0149\0\57\0\57\0\u0178\0\u01a7\0\u0178"+
    "\0\57\0\57\0\57\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a"+
    "\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524\0\57\0\u0553"+
    "\0\u0582\0\57\0\57\0\u05b1\0\u05e0\0\u060f\0\u01d6\0\u063e"+
    "\0\u066d\0\57\0\u069c\0\u06cb\0\136\0\136\0\u06fa\0\u0729"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19"+
    "\0\u0a48\0\57\0\57\0\u0a77\0\136\0\136\0\u0aa6\0\u0ad5"+
    "\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0582\0\57"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\136\0\u0cda\0\u0d09\0\u0d38"+
    "\0\136\0\u0d67\0\u0d96\0\136\0\u0dc5\0\u0df4\0\u0e23\0\u0e52"+
    "\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\136\0\u0f3d\0\u0f6c\0\u0f9b"+
    "\0\u0fca\0\u0ff9\0\136\0\136\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\136\0\57"+
    "\0\u11fe\0\136\0\u122d\0\57\0\136\0\u125c\0\136\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u1347\0\136\0\136\0\u1376\0\u13a5"+
    "\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d"+
    "\0\136\0\u154c\0\u157b\0\u15aa\0\57\0\136\0\57\0\136"+
    "\0\136\0\u15d9\0\u1608\0\u1637\0\u1666\0\136\0\136\0\57"+
    "\0\136\0\u1695\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af"+
    "\0\57\0\136\0\u17de\0\u180d\0\u183c\0\u186b\0\136\0\u189a"+
    "\0\u18c9\0\u18f8\0\u1927\0\57\0\136\0\u1956\0\u1985\0\u19b4"+
    "\0\136\0\u19e3\0\u1a12\0\u1a41\0\u1a70\0\u1a9f\0\57\0\136"+
    "\0\u1ace\0\u1afd\0\u1b2c\0\57\0\136\0\u1b5b\0\57\0\136"+
    "\0\u1b8a\0\57\0\u0bef\0\136\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\4\2\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\3\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\3\1\42\1\43\1\44\2\3\1\45"+
    "\1\46\1\47\60\0\1\3\13\0\1\50\12\0\13\3"+
    "\1\0\4\3\1\0\5\3\3\0\1\4\4\0\1\51"+
    "\56\0\1\52\67\0\1\53\37\0\2\54\1\0\7\54"+
    "\1\55\1\0\4\54\1\0\2\54\1\0\2\54\1\0"+
    "\13\54\1\0\4\54\1\0\5\54\3\0\1\4\13\0"+
    "\1\56\60\0\1\15\56\0\1\15\2\0\1\15\34\0"+
    "\12\57\1\60\1\0\4\57\1\61\2\57\1\0\2\57"+
    "\1\62\13\57\1\0\4\57\1\0\5\57\2\0\1\3"+
    "\13\0\1\50\12\0\1\3\1\63\1\3\1\64\7\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\10\3\1\65\1\3\1\66\1\0\4\3\1\0"+
    "\2\3\1\67\2\3\2\0\1\3\13\0\1\50\12\0"+
    "\1\3\1\70\11\3\1\0\4\3\1\0\5\3\2\0"+
    "\1\3\13\0\1\50\12\0\2\3\1\71\2\3\1\72"+
    "\5\3\1\0\3\3\1\73\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\5\3\1\74\2\3\1\75\2\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\13\3\1\0\4\3\1\0\2\3\1\76\2\3"+
    "\2\0\1\3\13\0\1\50\12\0\1\3\1\77\5\3"+
    "\1\100\3\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\3\3\1\101\1\102\6\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\7\3\1\103\1\104\2\3\1\0\4\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\50\12\0\1\3\1\105\1\106"+
    "\1\3\1\107\6\3\1\0\4\3\1\0\2\3\1\110"+
    "\2\3\36\0\1\111\4\0\1\112\5\0\2\113\6\0"+
    "\1\3\13\0\1\50\12\0\5\3\1\114\4\3\1\115"+
    "\1\0\4\3\1\113\1\116\4\3\2\0\1\3\13\0"+
    "\1\50\12\0\3\3\1\117\7\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\1\3\1\120"+
    "\11\3\1\0\4\3\1\0\5\3\42\0\1\121\16\0"+
    "\1\3\13\0\1\50\12\0\11\3\1\122\1\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\10\3\1\123\2\3\1\0\4\3\1\0\2\3\1\124"+
    "\2\3\2\0\1\3\13\0\1\50\12\0\7\3\1\125"+
    "\3\3\1\0\4\3\1\0\5\3\2\0\2\126\25\0"+
    "\13\126\1\0\4\126\1\0\5\126\3\0\1\127\65\0"+
    "\1\130\61\0\1\54\43\0\2\56\1\0\7\56\1\131"+
    "\1\0\4\56\1\132\2\56\1\0\2\56\1\0\13\56"+
    "\1\0\4\56\1\0\5\56\15\0\1\57\62\0\1\57"+
    "\37\0\1\3\13\0\1\50\12\0\1\3\1\133\11\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\13\3\1\0\1\3\1\134\2\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\50\12\0\11\3\1\135\1\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\1\3\1\136\11\3\1\0\4\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\50\12\0\13\3\1\0\4\3"+
    "\1\137\1\140\4\3\2\0\1\3\13\0\1\50\12\0"+
    "\13\3\1\0\2\3\1\141\1\3\1\0\5\3\2\0"+
    "\1\3\13\0\1\50\12\0\13\3\1\142\1\143\3\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\13\3"+
    "\1\0\2\3\1\144\1\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\10\3\1\145\2\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\2\3"+
    "\1\146\10\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\5\3\1\147\5\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\4\3"+
    "\1\150\6\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\11\3\1\151\1\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\5\3"+
    "\1\152\5\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\3\3\1\153\7\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\13\3"+
    "\1\0\4\3\1\0\2\3\1\154\2\3\2\0\1\3"+
    "\13\0\1\50\12\0\10\3\1\155\2\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\1\3"+
    "\1\156\11\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\2\3\1\157\10\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\5\3"+
    "\1\160\5\3\1\0\4\3\1\0\5\3\42\0\1\161"+
    "\16\0\1\3\13\0\1\50\12\0\11\3\1\162\1\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\11\3\1\163\1\3\1\0\4\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\50\12\0\10\3\1\164\2\3"+
    "\1\0\4\3\1\0\5\3\41\0\1\165\17\0\1\3"+
    "\13\0\1\50\12\0\10\3\1\166\2\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\1\3"+
    "\1\167\11\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\11\3\1\170\1\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\3\3"+
    "\1\171\7\3\1\172\1\173\3\3\1\0\5\3\2\0"+
    "\2\126\12\0\1\50\12\0\13\126\1\0\4\126\1\0"+
    "\5\126\15\0\1\56\62\0\1\56\37\0\1\3\13\0"+
    "\1\50\12\0\2\3\1\174\10\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\13\3\1\175"+
    "\1\176\3\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\13\3\1\0\4\3\1\0\3\3\1\177\1\3"+
    "\34\0\1\200\7\0\2\201\13\0\1\3\13\0\1\50"+
    "\12\0\3\3\1\202\7\3\1\201\1\203\3\3\1\0"+
    "\5\3\42\0\1\204\16\0\1\3\13\0\1\50\12\0"+
    "\11\3\1\205\1\3\1\0\4\3\1\0\5\3\2\0"+
    "\1\3\13\0\1\50\12\0\4\3\1\206\6\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\2\3\1\207\10\3\1\0\4\3\1\0\5\3\2\0"+
    "\1\3\13\0\1\50\12\0\13\3\1\0\4\3\1\210"+
    "\1\211\4\3\2\0\1\3\13\0\1\50\12\0\10\3"+
    "\1\212\2\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\13\3\1\0\4\3\1\0\2\3"+
    "\1\213\2\3\2\0\1\3\13\0\1\50\12\0\13\3"+
    "\1\0\1\3\1\214\2\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\5\3\1\215\5\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\3\3"+
    "\1\216\7\3\1\0\4\3\1\0\5\3\2\0\1\3"+
    "\13\0\1\50\12\0\4\3\1\217\6\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\13\3"+
    "\1\0\4\3\1\220\1\221\4\3\2\0\1\3\13\0"+
    "\1\50\12\0\6\3\1\222\4\3\1\0\4\3\1\0"+
    "\5\3\34\0\1\223\24\0\1\3\13\0\1\50\12\0"+
    "\3\3\1\224\7\3\1\0\4\3\1\0\5\3\44\0"+
    "\2\225\13\0\1\3\13\0\1\50\12\0\13\3\1\225"+
    "\1\226\3\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\6\3\1\227\4\3\1\0\4\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\230\12\0\13\3\1\0\4\3"+
    "\1\0\5\3\2\0\1\3\13\0\1\50\12\0\5\3"+
    "\1\231\5\3\1\0\4\3\1\0\5\3\33\0\1\232"+
    "\25\0\1\3\13\0\1\50\12\0\2\3\1\233\10\3"+
    "\1\0\4\3\1\0\5\3\2\0\1\3\13\0\1\50"+
    "\12\0\3\3\1\234\7\3\1\0\4\3\1\0\5\3"+
    "\36\0\1\235\22\0\1\3\13\0\1\50\12\0\5\3"+
    "\1\236\5\3\1\0\4\3\1\0\5\3\43\0\1\237"+
    "\15\0\1\3\13\0\1\50\12\0\12\3\1\240\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\13\3\1\0\4\3\1\0\1\3\1\241\3\3\42\0"+
    "\1\242\16\0\1\3\13\0\1\50\12\0\11\3\1\243"+
    "\1\3\1\0\4\3\1\0\5\3\2\0\1\3\13\0"+
    "\1\50\12\0\4\3\1\244\6\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\10\3\1\245"+
    "\2\3\1\0\4\3\1\0\5\3\2\0\1\3\13\0"+
    "\1\50\12\0\3\3\1\246\7\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\11\3\1\247"+
    "\1\3\1\0\4\3\1\0\5\3\34\0\1\250\24\0"+
    "\1\3\13\0\1\50\12\0\3\3\1\251\7\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\11\3\1\252\1\3\1\0\4\3\1\0\5\3\46\0"+
    "\1\253\12\0\1\3\13\0\1\50\12\0\13\3\1\0"+
    "\1\3\1\254\2\3\1\0\5\3\36\0\1\255\22\0"+
    "\1\3\13\0\1\50\12\0\5\3\1\256\5\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\3\3\1\257\7\3\1\0\4\3\1\0\5\3\2\0"+
    "\2\126\25\0\2\126\1\260\10\126\1\0\4\126\1\0"+
    "\5\126\34\0\1\261\24\0\1\3\13\0\1\50\12\0"+
    "\3\3\1\262\7\3\1\0\4\3\1\0\5\3\2\0"+
    "\1\3\13\0\1\50\12\0\4\3\1\263\6\3\1\0"+
    "\4\3\1\0\5\3\35\0\1\264\23\0\1\3\13\0"+
    "\1\50\12\0\4\3\1\265\6\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\6\3\1\266"+
    "\4\3\1\0\4\3\1\0\5\3\2\0\1\3\13\0"+
    "\1\50\12\0\5\3\1\267\5\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\13\3\1\270"+
    "\1\271\3\3\1\0\5\3\34\0\1\272\24\0\1\3"+
    "\13\0\1\50\12\0\3\3\1\273\7\3\1\0\4\3"+
    "\1\0\5\3\46\0\1\274\12\0\1\3\13\0\1\50"+
    "\12\0\13\3\1\0\1\3\1\275\2\3\1\0\5\3"+
    "\2\0\1\3\13\0\1\50\12\0\13\3\1\0\2\3"+
    "\1\276\1\3\1\0\5\3\2\0\2\126\12\0\1\50"+
    "\12\0\13\126\1\277\1\300\3\126\1\0\5\126\2\0"+
    "\1\3\13\0\1\50\12\0\5\3\1\301\5\3\1\0"+
    "\4\3\1\0\5\3\36\0\1\302\22\0\1\3\13\0"+
    "\1\50\12\0\5\3\1\303\5\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\11\3\1\304"+
    "\1\3\1\0\4\3\1\0\5\3\32\0\1\305\26\0"+
    "\1\3\13\0\1\50\12\0\1\3\1\306\11\3\1\0"+
    "\4\3\1\0\5\3\41\0\1\307\17\0\1\3\13\0"+
    "\1\50\12\0\10\3\1\310\2\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\13\3\1\0"+
    "\4\3\1\0\2\3\1\311\2\3\36\0\1\312\22\0"+
    "\2\126\12\0\1\50\12\0\5\126\1\313\5\126\1\0"+
    "\4\126\1\0\5\126\42\0\1\314\16\0\1\3\13\0"+
    "\1\50\12\0\11\3\1\315\1\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\3\3\1\316"+
    "\7\3\1\0\4\3\1\0\5\3\36\0\1\317\22\0"+
    "\1\3\13\0\1\50\12\0\5\3\1\320\5\3\1\0"+
    "\4\3\1\0\5\3\2\0\1\3\13\0\1\50\12\0"+
    "\10\3\1\321\2\3\1\0\4\3\1\0\5\3\34\0"+
    "\1\322\24\0\2\126\12\0\1\50\12\0\3\126\1\323"+
    "\7\126\1\0\4\126\1\0\5\126\2\0\1\3\13\0"+
    "\1\50\12\0\10\3\1\324\2\3\1\0\4\3\1\0"+
    "\5\3\2\0\1\3\13\0\1\50\12\0\3\3\1\325"+
    "\7\3\1\0\4\3\1\0\5\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7097];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\3\11\4\1\2\11\3\1\3\11"+
    "\23\1\1\11\2\0\2\11\2\0\1\1\3\0\1\11"+
    "\27\1\2\11\5\1\1\0\6\1\1\11\2\0\4\1"+
    "\1\0\2\1\1\0\16\1\1\0\3\1\1\0\4\1"+
    "\1\0\2\1\1\0\2\1\1\11\1\0\2\1\1\11"+
    "\3\1\1\0\7\1\1\0\2\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\11\1\1\1\11"+
    "\2\1\1\0\5\1\1\11\2\1\1\0\1\1\1\0"+
    "\3\1\1\11\2\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\11\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\11\2\1\1\0\1\1\1\11\2\1\1\11"+
    "\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public static ArrayList<String> ErroresLexicos = new ArrayList<String>();    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 248) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error lexico : " + yytext() + " en la linea: " + (yyline+1) + " y columna " + (yycolumn+1));
        ErroresLexicos.add("Error lexico : " + yytext() + " en la linea: " + (yyline+1) + " y columna " + (yycolumn+1));
            } 
            // fall through
          case 53: break;
          case 2: 
            { return new Symbol(sym.ID, yycolumn, yyline, new String(yytext()));
            } 
            // fall through
          case 54: break;
          case 3: 
            { return new Symbol(sym.NUM, yycolumn, yyline, new String(yytext()));
            } 
            // fall through
          case 55: break;
          case 4: 
            { 
            } 
            // fall through
          case 56: break;
          case 5: 
            { return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            } 
            // fall through
          case 57: break;
          case 6: 
            { return new Symbol(sym.SEMICOLON, yycolumn, yyline, yytext());
            } 
            // fall through
          case 58: break;
          case 7: 
            { return new Symbol(sym.DECLARACION, yycolumn, yyline, yytext());
            } 
            // fall through
          case 59: break;
          case 8: 
            { return new Symbol(sym.OPSUMA, yycolumn, yyline, yytext());
            } 
            // fall through
          case 60: break;
          case 9: 
            { return new Symbol(sym.OPMULTIPLICACION, yycolumn, yyline, yytext());
            } 
            // fall through
          case 61: break;
          case 10: 
            { return new Symbol(sym.OPREL, yycolumn, yyline, yytext());
            } 
            // fall through
          case 62: break;
          case 11: 
            { return new Symbol(sym.PARIZQ, yycolumn, yyline, yytext());
            } 
            // fall through
          case 63: break;
          case 12: 
            { return new Symbol(sym.PARDER, yycolumn, yyline, yytext());
            } 
            // fall through
          case 64: break;
          case 13: 
            { System.out.print(yytext());
            } 
            // fall through
          case 65: break;
          case 14: 
            { return new Symbol(sym.DOSPUNTOS, yycolumn, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 15: 
            { return new Symbol(sym.ASIGNACION, yycolumn, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 16: 
            { return new Symbol(sym.STRING, yycolumn, yyline, new String(yytext()));
            } 
            // fall through
          case 68: break;
          case 17: 
            { return new Symbol(sym.OR, yycolumn, yyline, yytext());
            } 
            // fall through
          case 69: break;
          case 18: 
            { return new Symbol(sym.OF, yycolumn, yyline, yytext());
            } 
            // fall through
          case 70: break;
          case 19: 
            { return new Symbol(sym.IN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 71: break;
          case 20: 
            { return new Symbol(sym.IF, yycolumn, yyline, yytext());
            } 
            // fall through
          case 72: break;
          case 21: 
            { return new Symbol(sym.IS, yycolumn, yyline, yytext());
            } 
            // fall through
          case 73: break;
          case 22: 
            { return new Symbol(sym.CHAR, yycolumn, yyline, new String(yytext()));
            } 
            // fall through
          case 74: break;
          case 23: 
            { return new Symbol(sym.OUT, yycolumn, yyline, yytext());
            } 
            // fall through
          case 75: break;
          case 24: 
            { return new Symbol(sym.END, yycolumn, yyline, yytext());
            } 
            // fall through
          case 76: break;
          case 25: 
            { return new Symbol(sym.AND, yycolumn, yyline, yytext());
            } 
            // fall through
          case 77: break;
          case 26: 
            { return new Symbol(sym.FOR, yycolumn, yyline, yytext());
            } 
            // fall through
          case 78: break;
          case 27: 
            { return new Symbol(sym.GET, yycolumn, yyline, yytext());
            } 
            // fall through
          case 79: break;
          case 28: 
            { return new Symbol(sym.XOR, yycolumn, yyline, yytext());
            } 
            // fall through
          case 80: break;
          case 29: 
            { return new Symbol(sym.PUT, yycolumn, yyline, yytext());
            } 
            // fall through
          case 81: break;
          case 30: 
            { return new Symbol(sym.LOOP, yycolumn, yyline, yytext());
            } 
            // fall through
          case 82: break;
          case 31: 
            { return new Symbol(sym.ELSE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 83: break;
          case 32: 
            { return new Symbol(sym.EXIT, yycolumn, yyline, yytext());
            } 
            // fall through
          case 84: break;
          case 33: 
            { return new Symbol(sym.NULL, yycolumn, yyline, yytext());
            } 
            // fall through
          case 85: break;
          case 34: 
            { return new Symbol(sym.THEN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 86: break;
          case 35: 
            { return new Symbol(sym.TRUE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 87: break;
          case 36: 
            { return new Symbol(sym.WHEN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 88: break;
          case 37: 
            { return new Symbol(sym.BEGIN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 89: break;
          case 38: 
            { return new Symbol(sym.ELSIF, yycolumn, yyline, yytext());
            } 
            // fall through
          case 90: break;
          case 39: 
            { return new Symbol(sym.ARRAY, yycolumn, yyline, yytext());
            } 
            // fall through
          case 91: break;
          case 40: 
            { return new Symbol(sym.RANGE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 92: break;
          case 41: 
            { return new Symbol(sym.FLOAT, yycolumn, yyline, yytext());
            } 
            // fall through
          case 93: break;
          case 42: 
            { return new Symbol(sym.FALSE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 94: break;
          case 43: 
            { return new Symbol(sym.WHILE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 95: break;
          case 44: 
            { return new Symbol(sym.RETURN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 96: break;
          case 45: 
            { return new Symbol(sym.STRINGTYPE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 97: break;
          case 46: 
            { return new Symbol(sym.BOOLEAN, yycolumn, yyline, yytext());
            } 
            // fall through
          case 98: break;
          case 47: 
            { return new Symbol(sym.INTEGER, yycolumn, yyline, yytext());
            } 
            // fall through
          case 99: break;
          case 48: 
            { return new Symbol(sym.CONSTANT, yycolumn, yyline, yytext());
            } 
            // fall through
          case 100: break;
          case 49: 
            { return new Symbol(sym.FUNCTION, yycolumn, yyline, yytext());
            } 
            // fall through
          case 101: break;
          case 50: 
            { return new Symbol(sym.PUT_LINE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 102: break;
          case 51: 
            { return new Symbol(sym.CHARACTER, yycolumn, yyline, yytext());
            } 
            // fall through
          case 103: break;
          case 52: 
            { return new Symbol(sym.PROCEDURE, yycolumn, yyline, yytext());
            } 
            // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
