
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 40;
  public static final int WHEN = 23;
  public static final int FUNCTION = 3;
  public static final int PUT = 26;
  public static final int ENTERO = 45;
  public static final int ELSIF = 11;
  public static final int XOR = 19;
  public static final int INTEGER = 27;
  public static final int OUT = 14;
  public static final int FOR = 12;
  public static final int SEMICOLON = 38;
  public static final int OPSUMA = 35;
  public static final int IS = 5;
  public static final int AND = 17;
  public static final int IN = 13;
  public static final int OR = 18;
  public static final int GET = 25;
  public static final int BEGIN = 6;
  public static final int OPREL = 33;
  public static final int NUM = 43;
  public static final int LOOP = 16;
  public static final int EXIT = 22;
  public static final int IF = 8;
  public static final int ID = 42;
  public static final int PARIZQ = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int RETURN = 4;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int NULL = 24;
  public static final int ASIGNACION = 31;
  public static final int DECLARACION = 32;
  public static final int ELSE = 10;
  public static final int PUNTO = 41;
  public static final int WHILE = 15;
  public static final int STRINGTYPE = 30;
  public static final int FLOAT = 28;
  public static final int THEN = 9;
  public static final int OPMULTIPLICACION = 34;
  public static final int END = 7;
  public static final int BOOLEANO = 48;
  public static final int NUMFLOAT = 46;
  public static final int STRING = 44;
  public static final int TEXTO = 47;
  public static final int PARDER = 36;
  public static final int FALSE = 20;
  public static final int PROCEDURE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "FUNCTION",
  "RETURN",
  "IS",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "FOR",
  "IN",
  "OUT",
  "WHILE",
  "LOOP",
  "AND",
  "OR",
  "XOR",
  "FALSE",
  "TRUE",
  "EXIT",
  "WHEN",
  "NULL",
  "GET",
  "PUT",
  "INTEGER",
  "FLOAT",
  "BOOLEAN",
  "STRINGTYPE",
  "ASIGNACION",
  "DECLARACION",
  "OPREL",
  "OPMULTIPLICACION",
  "OPSUMA",
  "PARDER",
  "PARIZQ",
  "SEMICOLON",
  "COMA",
  "DOSPUNTOS",
  "PUNTO",
  "ID",
  "NUM",
  "STRING",
  "ENTERO",
  "NUMFLOAT",
  "TEXTO",
  "BOOLEANO"
  };
}

