
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 41;
  public static final int WHEN = 24;
  public static final int FUNCTION = 3;
  public static final int PUT = 27;
  public static final int ENTERO = 45;
  public static final int ELSIF = 12;
  public static final int XOR = 20;
  public static final int INTEGER = 28;
  public static final int OUT = 15;
  public static final int FOR = 13;
  public static final int SEMICOLON = 39;
  public static final int OPSUMA = 36;
  public static final int IS = 6;
  public static final int AND = 18;
  public static final int IN = 14;
  public static final int OR = 19;
  public static final int GET = 26;
  public static final int BEGIN = 7;
  public static final int OPREL = 34;
  public static final int NUM = 43;
  public static final int LOOP = 17;
  public static final int EXIT = 23;
  public static final int IF = 9;
  public static final int ID = 42;
  public static final int PARIZQ = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 30;
  public static final int RETURN = 4;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int NULL = 25;
  public static final int CONSTANT = 5;
  public static final int ASIGNACION = 32;
  public static final int DECLARACION = 33;
  public static final int ELSE = 11;
  public static final int WHILE = 16;
  public static final int STRINGTYPE = 31;
  public static final int FLOAT = 29;
  public static final int THEN = 10;
  public static final int OPMULTIPLICACION = 35;
  public static final int END = 8;
  public static final int BOOLEANO = 48;
  public static final int NUMFLOAT = 46;
  public static final int STRING = 44;
  public static final int TEXTO = 47;
  public static final int PARDER = 37;
  public static final int FALSE = 21;
  public static final int PROCEDURE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "FUNCTION",
  "RETURN",
  "CONSTANT",
  "IS",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "FOR",
  "IN",
  "OUT",
  "WHILE",
  "LOOP",
  "AND",
  "OR",
  "XOR",
  "FALSE",
  "TRUE",
  "EXIT",
  "WHEN",
  "NULL",
  "GET",
  "PUT",
  "INTEGER",
  "FLOAT",
  "BOOLEAN",
  "STRINGTYPE",
  "ASIGNACION",
  "DECLARACION",
  "OPREL",
  "OPMULTIPLICACION",
  "OPSUMA",
  "PARDER",
  "PARIZQ",
  "SEMICOLON",
  "COMA",
  "DOSPUNTOS",
  "ID",
  "NUM",
  "STRING",
  "ENTERO",
  "NUMFLOAT",
  "TEXTO",
  "BOOLEANO"
  };
}

