
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROCEDURE = 2;
  public static final int AND = 21;
  public static final int IS = 7;
  public static final int ELSE = 13;
  public static final int ELSIF = 14;
  public static final int THEN = 12;
  public static final int WHILE = 18;
  public static final int IN = 16;
  public static final int LOOP = 19;
  public static final int CONSTANT = 6;
  public static final int END = 10;
  public static final int RETURN = 4;
  public static final int FUNCTION = 3;
  public static final int IF = 11;
  public static final int DO = 20;
  public static final int BEGIN = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OUT = 17;
  public static final int FOR = 15;
  public static final int ARRAY = 5;
  public static final int DECLARE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "FUNCTION",
  "RETURN",
  "ARRAY",
  "CONSTANT",
  "IS",
  "DECLARE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "FOR",
  "IN",
  "OUT",
  "WHILE",
  "LOOP",
  "DO",
  "AND"
  };
}

